name: My First Workflow
run-name : Run Name ${{ github.run_id}} / ${{ github.run_attempt}} / ${{ github.run_number }}
on: push

jobs:
  foo:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: printenv
  bar:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/sdk:latest
    permissions: write-all
    steps:
      - run: printenv  

  foobar:
    runs-on: ubuntu-latest
    needs: [foo, bar]
    steps:
      - run: echo En klaar
    



                

        
  

  