name: My First Workflow
run-name : Run Name ${{ github.run_id}} / ${{ github.run_attempt}} / ${{ github.run_number }}
on: push

jobs:
 

  foo:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      CONTEXT: ${{ toJson(github) }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
        run: printenv
      - name: Print github
        run: echo $CONTEXT
  bar:
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:latest
    permissions: write-all
    steps:
      - run: printenv  

  foobar:
    runs-on: ubuntu-latest
    needs: [foo, bar]
    steps:
      - run: echo En klaar
    



                

        
  

  