name: My First Workflow
run-name : Run Name ${{ github.run_id}} / ${{ github.run_attempt}} / ${{ github.run_number }}
on: push

jobs:
    build:
        name: Build job
        runs-on: ubuntu-latest
        env:
          A : 1234
          B : 4567


        steps:
            - name: Checkout files
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0 
            - name: Show files
              run: ls


            - name: Setup container
              uses: docker/setup-buildx-action@v3

            - name: Login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ghcr.io/${{ github.repository}}/myapp:latest
                push: true
                


                

        
  

  