name: My First Workflow
run-name : Run Name
on: push

jobs:
    build:
        name: Build job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout files
              uses: actions/checkout@v4

        
  

  