name: My First Workflow
run-name : Run Name
on: push

jobs:
    build:
        name: Build job
        runs-on: ubuntu-latest
        env:
          A : 1234
          B : 4567


        steps:
            - name: Checkout files
              uses: actions/checkout@v4

        
  

  